services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_ARBITRARY: 1
    networks:
      - serversNET
    volumes:
      - config.inc.php:/etc/phpmyadmin/config.inc.php 

networks:
  serversNET:
    external: true